enableEmoji = true
enableRobotsTXT = true
disqusShortname = "goldcoders"
languageCode = "en-us"
googleAnalytics = ""
summaryLength = "10"
title = "Thriftshop Site"
baseURL = "https://thriftshop.site/"
paginate = 9
ignoreErrors = ["error-missing-instagram-accesstoken", "error-remote-getjson"]

[permalinks]
blogs = "/blog/:slug/"
products = "/products/:slug/"
pages = "/:slug"

[author]
homepage = "https://github.com/goldcoders"
name = "Goldcoders"
avatar = "/images/avatar.svg"

[build]
noJSConfigInAssets = false
useResourceCacheWhen = "fallback"
writeStats = true