github_user = "goldcoders"
mainSections = ["blog", "products"]
copyright = "Copyright © 2020, GOLDCODERS CORP™️., all rights reserved."
github_banner = true
github_repo = "https://github.com/thrift-shop-site/theme"
favicon = "/images/logo.png"
description = "The Most Affordable Ecommerce Site For Filipino Online Seller Startups"

[gtm]
enable = false
id = ""

[navbar]
color = "primary-darker"
shade = ""

[logo]
image = "/images/Thrifthshop-Apps-Logo-T-White.png"
height = "16"

[brand]
enable = true
name = "Thriftshop"
font = "aguafina"
color = "brand"
shade = ""

[tag]
name = "SITE"
font = "steel"
color = "white"
shade = ""

[cover_photo]
color = "gray"
shade = "50"
font = "aguafina"

[placeholder]
cover_photo = "https://cdn.pixabay.com/photo/2015/03/26/09/40/business-suit-690048_960_720.jpg"
post = "https://via.placeholder.com/760x450"